dist: trusty
sudo: required

language: cpp

compiler: g++

addons:
  sonarcloud:
    organization: "gautierbureau-github"
    token:
      secure: ${SONAR_TOKEN}

install:
  - sudo apt-get install gcovr realpath lcov
  - gem install coveralls-lcov
  - CHECKOUT_COMMIT=$(git rev-parse HEAD)
  - echo $CHECKOUT_COMMIT
  - echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
  - echo TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_BRANCH $TRAVIS_BRANCH
  - echo TRAVIS_EVENT_TYPE $TRAVIS_EVENT_TYPE
  - echo TRAVIS $TRAVIS
  - echo CI $CI
  - BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - echo $(git rev-parse --abbrev-ref HEAD)
  - git_command=$(./checkout_commit.sh)
  - echo $git_command
  - (cd /tmp;wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz;tar -xzf release-1.8.1.tar.gz;cd googletest-release-1.8.1;mkdir build;cd build;cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON ..;make;sudo make install)

script:
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - ./compile.sh build-tests
  - ls coverage
  # - cat coverage/report.xml
  - build-wrapper-linux-x86-64 --out-dir bw-output ./build_sonar.sh
  - sonar-scanner
  - coveralls-lcov -t $COVERALLS_TOKEN coverage.info
