dist: trusty

language: cpp

compiler: g++

install:
  - CHECKOUT_COMMIT=$(git rev-parse HEAD)
  - echo $CHECKOUT_COMMIT
  - echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
  - echo TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_BRANCH $TRAVIS_BRANCH
  - echo TRAVIS_EVENT_TYPE $TRAVIS_EVENT_TYPE
  - echo TRAVIS $TRAVIS
  - echo CI $CI
  - BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - echo $(git rev-parse --abbrev-ref HEAD)
  - git_command=$(./checkout_commit.sh)
  - echo $git_command

script:
  - echo toto
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_EVENT_TYPE" = "push" ]; echo sonar-scanner; fi